use std::process::Command;

use serde::Serialize;

use super::{CommandDescriptor, Provider, SearchResult};

#[derive(Debug, Clone, Serialize)]
pub struct Definition {
    pub pos: String,
    pub num: u32,
    pub text: String,
    pub quotes: Vec<String>,
    pub synonyms: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct DictResult {
    pub word: String,
    pub definitions: Vec<Definition>,
}

/// Frequency-ordered word list (line index = frequency rank, lower = commoner).
/// Baked into the binary so suggestions are fully offline - the `dict` binary
/// hits an online WordNet DB, so we never probe it to test spellings.
///
/// Generated by `tools/filter_wordlist.py`: google-10000-english intersected
/// with the WordNet lemma set, so every suggestion actually resolves in `dict`.
const WORDLIST: &str = include_str!("words_wn.txt");

/// Max suggestion rows appended after the literal typed word.
const MAX_SUGGESTIONS: usize = 8;
/// Below this many prefix hits we treat the input as a likely typo and run
/// spell correction; at/above it the input is a real stem, so corrections are
/// noise.
const PREFIX_SPARSE_THRESHOLD: usize = 3;

// ---- BK-tree (spell correction) -------------------------------------------

/// Optimal String Alignment distance (Damerau-Levenshtein restricted to
/// adjacent transpositions, so `recieve`/`receive` is distance 1).
fn osa_distance(a: &str, b: &str) -> usize {
    let a: Vec<char> = a.chars().collect();
    let b: Vec<char> = b.chars().collect();
    let (n, m) = (a.len(), b.len());
    if n == 0 {
        return m;
    }
    if m == 0 {
        return n;
    }
    let mut prev2 = vec![0usize; m + 1];
    let mut prev: Vec<usize> = (0..=m).collect();
    let mut cur = vec![0usize; m + 1];
    for i in 1..=n {
        cur[0] = i;
        for j in 1..=m {
            let cost = if a[i - 1] == b[j - 1] { 0 } else { 1 };
            let mut val = (prev[j] + 1).min(cur[j - 1] + 1).min(prev[j - 1] + cost);
            if i > 1 && j > 1 && a[i - 1] == b[j - 2] && a[i - 2] == b[j - 1] {
                val = val.min(prev2[j - 2] + 1);
            }
            cur[j] = val;
        }
        // rotate buffers: prev2 <- prev, prev <- cur, cur <- scratch
        std::mem::swap(&mut prev2, &mut cur);
        std::mem::swap(&mut prev2, &mut prev);
    }
    prev[m]
}

struct BkNode {
    word: Box<str>,
    rank: u32,
    /// (edge distance to child, child). Linear scan is fine - fan-out is tiny.
    children: Vec<(u8, BkNode)>,
}

impl BkNode {
    fn leaf(word: &str, rank: u32) -> Self {
        BkNode { word: word.into(), rank, children: Vec::new() }
    }

    fn insert(&mut self, word: &str, rank: u32) {
        let d = osa_distance(&self.word, word) as u8;
        if d == 0 {
            return; // duplicate
        }
        if let Some((_, child)) = self.children.iter_mut().find(|(e, _)| *e == d) {
            child.insert(word, rank);
        } else {
            self.children.push((d, BkNode::leaf(word, rank)));
        }
    }

    fn search(&self, word: &str, tol: u8, out: &mut Vec<(u32, u8)>) {
        let d = osa_distance(&self.word, word) as u8;
        if d <= tol {
            out.push((self.rank, d));
        }
        let lo = d.saturating_sub(tol);
        let hi = d.saturating_add(tol);
        for (e, child) in &self.children {
            // Triangle inequality: a match within tol of `word` is within
            // [d-tol, d+tol] of this node.
            if *e >= lo && *e <= hi {
                child.search(word, tol, out);
            }
        }
    }
}

struct BkTree {
    root: Option<BkNode>,
}

impl BkTree {
    fn new() -> Self {
        Self { root: None }
    }

    fn insert(&mut self, word: &str, rank: u32) {
        match &mut self.root {
            None => self.root = Some(BkNode::leaf(word, rank)),
            Some(root) => root.insert(word, rank),
        }
    }

    fn search(&self, word: &str, tol: u8, out: &mut Vec<(u32, u8)>) {
        if let Some(root) = &self.root {
            root.search(word, tol, out);
        }
    }
}

// ---- Embedded word index --------------------------------------------------

struct WordIndex {
    by_rank: Vec<Box<str>>,
    /// (word, rank) sorted alphabetically - prefix lookup via binary search.
    by_alpha: Vec<(Box<str>, u32)>,
    bk: BkTree,
}

impl WordIndex {
    fn build() -> Self {
        let mut by_rank: Vec<Box<str>> = Vec::new();
        for line in WORDLIST.lines() {
            let w = line.trim();
            if !w.is_empty() {
                by_rank.push(Box::from(w));
            }
        }
        let mut by_alpha: Vec<(Box<str>, u32)> = by_rank
            .iter()
            .enumerate()
            .map(|(r, w)| (w.clone(), r as u32))
            .collect();
        by_alpha.sort_by(|a, b| a.0.cmp(&b.0));

        let mut bk = BkTree::new();
        for (rank, w) in by_rank.iter().enumerate() {
            bk.insert(w, rank as u32);
        }

        Self { by_rank, by_alpha, bk }
    }

    fn word(&self, rank: u32) -> &str {
        &self.by_rank[rank as usize]
    }

    /// Ranks of words starting with `prefix`, frequency-ordered, up to `limit`.
    fn prefix_matches(&self, prefix: &str, limit: usize) -> Vec<u32> {
        let lo = self.by_alpha.partition_point(|(w, _)| w.as_ref() < prefix);
        let mut hits: Vec<u32> = self.by_alpha[lo..]
            .iter()
            .take_while(|(w, _)| w.starts_with(prefix))
            .map(|(_, r)| *r)
            .collect();
        hits.sort_unstable(); // u32 rank asc = frequency order
        hits.truncate(limit);
        hits
    }

    /// Sparse-fill candidate ranks for the typed word, ordered best-first.
    /// Every returned rank is a real wordlist lemma (so `dict` resolves it).
    /// `allow_typos` enables edit-distance corrections; otherwise only the
    /// exact lemma (if present) is returned.
    fn fill_matches(&self, word: &str, limit: usize, allow_typos: bool) -> Vec<u32> {
        if allow_typos {
            // corrections() is distance-then-frequency ordered; an exact match
            // is distance 0 and therefore comes first.
            return self.corrections(word, limit);
        }
        let lo = self.by_alpha.partition_point(|(w, _)| w.as_ref() < word);
        match self.by_alpha.get(lo) {
            Some((w, r)) if w.as_ref() == word => vec![*r],
            _ => Vec::new(),
        }
    }

    /// Spell-correction ranks, ordered by (distance asc, frequency asc).
    fn corrections(&self, word: &str, limit: usize) -> Vec<u32> {
        // Tight tolerance for short words so e.g. "cat" doesn't pull car/can/cab/...
        let tol: u8 = if word.chars().count() <= 4 { 1 } else { 2 };
        let mut out: Vec<(u32, u8)> = Vec::new();
        self.bk.search(word, tol, &mut out);
        out.sort_by(|a, b| a.1.cmp(&b.1).then(a.0.cmp(&b.0)));
        out.truncate(limit);
        out.into_iter().map(|(r, _)| r).collect()
    }
}

pub struct DictProvider {
    pub available: bool,
    index: WordIndex,
    fill_sparse: bool,
    correct_misspellings: bool,
    fill_max: usize,
}

impl DictProvider {
    pub fn new(cfg: &crate::config::DictConfig) -> Self {
        let available = Command::new("dict").arg("--version").output().is_ok();
        Self {
            available,
            index: WordIndex::build(),
            fill_sparse: cfg.fill_sparse,
            correct_misspellings: cfg.correct_misspellings,
            fill_max: cfg.fill_max,
        }
    }

    /// Sparse-fill rows for a plain (non-prefixed) query. Returns only words
    /// that exist in the embedded wordlist - if the query is neither a lemma
    /// nor (when enabled) close enough to correct, returns empty. Rows are
    /// low-scored so the registry keeps them only when results are sparse.
    fn fill_results(&self, query: &str) -> Vec<SearchResult> {
        let q = query.trim();
        if !self.fill_sparse || q.contains(' ') || q.chars().count() < 3 {
            return vec![];
        }
        let q_lc = q.to_lowercase();
        self.index
            .fill_matches(&q_lc, self.fill_max, self.correct_misspellings)
            .into_iter()
            .enumerate()
            .map(|(i, rank)| {
                let w = self.index.word(rank);
                dict_result(w, "WordNet dictionary", super::SCORE_DICT_FILL - i as f32 * 1e-3)
            })
            .collect()
    }
}

impl Provider for DictProvider {
    fn id(&self) -> &str {
        "dict"
    }

    fn search(&self, query: &str) -> Vec<SearchResult> {
        if !self.available {
            return vec![];
        }

        // Root search only offers sparse-fill candidates for the typed word:
        // only words present in the embedded wordlist are returned (so the
        // literal typed word is NOT emitted unless it's a real lemma), and the
        // registry keeps them only when other results are sparse. Explicit
        // lookups happen in the "Define Word" scope (search_scoped).
        self.fill_results(query.trim_end())
    }

    fn commands(&self) -> Vec<CommandDescriptor> {
        use crate::providers::command::{CommandRoute, CommandSource, ModeKind};
        if !self.available {
            return vec![];
        }
        vec![CommandDescriptor {
            id: "cmd:dict".to_string(),
            title: "Define Word".to_string(),
            chip: "Define".to_string(),
            subtitle: Some("WordNet dictionary".to_string()),
            source: CommandSource::Builtin,
            mode_kind: ModeKind::Scope,
            keywords: vec![
                "define".into(),
                "dict".into(),
                "dictionary".into(),
                "lookup".into(),
                "word".into(),
            ],
            placeholder: Some("Type a word to look it up…".to_string()),
            min_query_len: 1,
            result_kind: "dict".to_string(),
            glyph: Some("book".to_string()),
            icon_data_uri: None,
            opens_form: false,
            route: CommandRoute::Builtin { provider_id: "dict".to_string() },
        }]
    }

    // In the "Define Word" scope the whole query is the word - no prefix.
    fn search_scoped(&self, _command_id: &str, query: &str) -> Vec<SearchResult> {
        if !self.available {
            return vec![];
        }
        self.lookup(query.trim())
    }
}

impl DictProvider {
    /// Suggestion rows for an explicit lookup of `word`: the literal word
    /// first, then prefix completions, then (when the prefix is sparse) spell
    /// corrections. Serves only the embedded index - never calls `dict`, which
    /// would block the keystroke path; the preview fetches definitions
    /// asynchronously via get_dict_definitions.
    fn lookup(&self, word: &str) -> Vec<SearchResult> {
        if word.is_empty() {
            return vec![hint_result("Start typing a word to look it up\u{2026}")];
        }

        let word_lc = word.to_lowercase();
        let mut results: Vec<SearchResult> = Vec::new();
        let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();

        // 1. Literal typed word - always first, full score. Looks up anything,
        //    including words absent from the embedded list.
        results.push(dict_result(word, "WordNet dictionary", super::SCORE_DICT));
        seen.insert(word_lc.clone());

        // 2. Prefix autocomplete, frequency-ordered.
        let prefix_hits = self.index.prefix_matches(&word_lc, MAX_SUGGESTIONS);
        let prefix_count = prefix_hits.len();
        for (i, rank) in prefix_hits.into_iter().enumerate() {
            let w = self.index.word(rank);
            if seen.insert(w.to_string()) {
                let score = super::SCORE_DICT - 1.0 - i as f32 * 1e-3;
                results.push(dict_result(w, "WordNet dictionary", score));
            }
        }

        // 3. Spell correction - only when the prefix is sparse (likely a typo,
        //    not a real stem).
        if prefix_count < PREFIX_SPARSE_THRESHOLD {
            let base = super::SCORE_DICT - 1000.0;
            for (i, rank) in self
                .index
                .corrections(&word_lc, MAX_SUGGESTIONS)
                .into_iter()
                .enumerate()
            {
                let w = self.index.word(rank);
                if seen.insert(w.to_string()) {
                    let score = base - i as f32 * 1e-3;
                    results.push(dict_result(w, "WordNet dictionary", score));
                }
            }
        }

        results.truncate(MAX_SUGGESTIONS + 1);
        results
    }
}

fn dict_result(word: &str, subtitle: &str, score: f32) -> SearchResult {
    SearchResult {
        id: format!("dict:{word}"),
        title: word.to_string(),
        subtitle: Some(subtitle.to_string()),
        kind: "dict".to_string(),
        score,
        ..Default::default()
    }
}

fn hint_result(subtitle: &str) -> SearchResult {
    SearchResult {
        id: "dict:hint".to_string(),
        title: "define word".to_string(),
        subtitle: Some(subtitle.to_string()),
        kind: "dict-hint".to_string(),
        score: super::SCORE_DICT,
        ..Default::default()
    }
}

fn is_not_found(output: &str) -> bool {
    output.contains("No definitions found")
        || output.contains("No matches found")
        || output.trim().is_empty()
}

fn expand_pos(code: &str) -> &'static str {
    match code {
        "n" => "Noun",
        "v" => "Verb",
        "adj" | "s" => "Adjective",
        "adv" | "r" => "Adverb",
        _ => "Unknown",
    }
}

fn try_parse_def_start(s: &str) -> Option<(Option<String>, u32, String)> {
    // s is already trimmed of leading whitespace.
    // Patterns: "n 1: text", "2: text", "adv 3: text"
    let mut rest = s;
    let mut pos_code: Option<String> = None;

    // Check for optional POS prefix: lowercase letters then space then digit
    let alpha_len = rest.chars().take_while(|c| c.is_ascii_lowercase()).count();
    if alpha_len > 0 && alpha_len < rest.len() {
        let after_alpha = &rest[alpha_len..];
        if after_alpha.starts_with(' ') {
            let after_space = &after_alpha[1..];
            if after_space.chars().next().map_or(false, |c| c.is_ascii_digit()) {
                pos_code = Some(rest[..alpha_len].to_string());
                rest = after_space;
            }
        }
    }

    // Now rest should start with "N: " where N is one or more digits
    let digit_len = rest.chars().take_while(|c| c.is_ascii_digit()).count();
    if digit_len == 0 {
        return None;
    }
    let num: u32 = rest[..digit_len].parse().ok()?;
    let after_num = &rest[digit_len..];
    if !after_num.starts_with(": ") {
        return None;
    }
    Some((pos_code, num, after_num[2..].to_string()))
}

fn extract_synonyms(text: &str) -> Vec<String> {
    let mut syns = Vec::new();
    let mut s = text;
    while let Some(start) = s.find("[syn:") {
        let after = &s[start + 5..];
        let end = match after.find(']') {
            Some(e) => e,
            None => break,
        };
        let content = &after[..end];
        let mut c = content;
        while let Some(brace_start) = c.find('{') {
            c = &c[brace_start + 1..];
            if let Some(brace_end) = c.find('}') {
                let word = c[..brace_end].trim().to_string();
                if !word.is_empty() {
                    syns.push(word);
                }
                c = &c[brace_end + 1..];
            } else {
                break;
            }
        }
        s = &s[start + 5 + end + 1..];
    }
    syns
}

fn extract_quotes(text: &str) -> Vec<String> {
    let mut quotes = Vec::new();
    let mut s = text;
    while let Some(start) = s.find('"') {
        let after = &s[start + 1..];
        if let Some(end) = after.find('"') {
            let q = after[..end].trim().to_string();
            if !q.is_empty() {
                quotes.push(q);
            }
            s = &after[end + 1..];
        } else {
            break;
        }
    }
    quotes
}

fn strip_brackets(text: &str) -> String {
    let mut result = String::new();
    let mut s = text;
    while let Some(start) = s.find('[') {
        result.push_str(&s[..start]);
        if let Some(end) = s[start..].find(']') {
            s = &s[start + end + 1..];
        } else {
            result.push_str(&s[start..]);
            s = "";
            break;
        }
    }
    result.push_str(s);
    result
}

fn strip_inline_quotes(text: &str) -> String {
    let mut result = String::new();
    let mut s = text;
    while let Some(start) = s.find('"') {
        result.push_str(&s[..start]);
        let after = &s[start + 1..];
        if let Some(end) = after.find('"') {
            s = &after[end + 1..];
        } else {
            result.push_str(&s[start..]);
            s = "";
            break;
        }
    }
    result.push_str(s);
    result
}

fn build_def(pos: String, num: u32, raw: &str) -> Definition {
    let synonyms = extract_synonyms(raw);
    let quotes = extract_quotes(raw);

    let no_syn = strip_brackets(raw);
    let no_quotes = strip_inline_quotes(&no_syn);

    // Remove empty semicolon segments and normalize whitespace
    let text = no_quotes
        .split(';')
        .map(|s| s.split_whitespace().collect::<Vec<_>>().join(" "))
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("; ");

    Definition { pos, num, text, quotes, synonyms }
}

pub fn parse_full(output: &str, word: &str) -> DictResult {
    let mut defs: Vec<Definition> = Vec::new();
    let mut in_block = false;
    let mut current_pos = "Noun".to_string();
    let mut current_def_pos = current_pos.clone();
    let mut current_num: u32 = 0;
    let mut current_raw: Option<String> = None;

    for line in output.lines() {
        if line.trim_start().starts_with("From WordNet") {
            in_block = true;
            continue;
        }
        // Stop at the next database header (shouldn't happen with -d wn, but be safe)
        if in_block && line.trim_start().starts_with("From ") && !line.trim_start().starts_with("From WordNet") {
            break;
        }
        if !in_block {
            continue;
        }

        let leading = line.len() - line.trim_start().len();
        let trimmed = line.trim_start();

        if trimmed.is_empty() {
            continue;
        }
        // Skip the word header line (indented by only 2 spaces)
        if leading < 4 {
            continue;
        }

        if let Some((pos_opt, num, text)) = try_parse_def_start(trimmed) {
            // Finalize previous definition
            if let Some(raw) = current_raw.take() {
                defs.push(build_def(current_def_pos.clone(), current_num, &raw));
            }
            if let Some(pos) = pos_opt {
                current_pos = expand_pos(&pos).to_string();
            }
            current_def_pos = current_pos.clone();
            current_num = num;
            current_raw = Some(text);
        } else if let Some(ref mut raw) = current_raw {
            raw.push(' ');
            raw.push_str(trimmed);
        }
    }

    // Finalize last definition
    if let Some(raw) = current_raw {
        defs.push(build_def(current_def_pos, current_num, &raw));
    }

    DictResult { word: word.to_string(), definitions: defs }
}

#[tauri::command]
pub async fn get_dict_definitions(word: String) -> Result<DictResult, String> {
    tauri::async_runtime::spawn_blocking(move || {
        let output = std::process::Command::new("dict")
            .args(["-d", "wn", &word])
            .output()
            .map_err(|e| e.to_string())?;
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        if is_not_found(&stdout) {
            return Err("not_found".to_string());
        }
        Ok(parse_full(&stdout, &word))
    })
    .await
    .map_err(|e| e.to_string())?
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn osa_basic() {
        assert_eq!(osa_distance("", ""), 0);
        assert_eq!(osa_distance("abc", "abc"), 0);
        assert_eq!(osa_distance("abc", ""), 3);
        assert_eq!(osa_distance("cat", "cab"), 1); // substitution
        assert_eq!(osa_distance("cat", "cats"), 1); // insertion
    }

    #[test]
    fn osa_transposition_is_one() {
        // The whole reason for OSA over plain Levenshtein.
        assert_eq!(osa_distance("recieve", "receive"), 1);
        assert_eq!(osa_distance("teh", "the"), 1);
    }

    #[test]
    fn bktree_finds_within_tolerance() {
        let mut bk = BkTree::new();
        for (rank, w) in ["receive", "recipe", "recent", "cat"].iter().enumerate() {
            bk.insert(w, rank as u32);
        }
        let mut out = Vec::new();
        bk.search("recieve", 2, &mut out);
        let words: Vec<&str> = out.iter().map(|(r, _)| ["receive", "recipe", "recent", "cat"][*r as usize]).collect();
        assert!(words.contains(&"receive"), "got {words:?}");
        assert!(!words.contains(&"cat"), "cat is too far, got {words:?}");
    }

    #[test]
    fn index_corrects_misspelling() {
        let idx = WordIndex::build();
        let ranks = idx.corrections("recieve", 8);
        let words: Vec<&str> = ranks.iter().map(|r| idx.word(*r)).collect();
        assert!(words.contains(&"receive"), "got {words:?}");
    }

    #[test]
    fn fill_matches_exact_only() {
        let idx = WordIndex::build();
        // Exact lemma resolves to itself; a typo resolves to nothing.
        let exact = idx.fill_matches("receive", 5, false);
        assert_eq!(exact.iter().map(|r| idx.word(*r)).collect::<Vec<_>>(), ["receive"]);
        assert!(idx.fill_matches("recieve", 5, false).is_empty());
        // A non-word resolves to nothing even in exact mode.
        assert!(idx.fill_matches("zzzxqq", 5, false).is_empty());
    }

    #[test]
    fn fill_matches_corrects_when_typos_allowed() {
        let idx = WordIndex::build();
        let words: Vec<&str> =
            idx.fill_matches("recieve", 5, true).iter().map(|r| idx.word(*r)).collect();
        assert!(words.contains(&"receive"), "got {words:?}");
    }

    #[test]
    fn index_prefix_is_frequency_ordered() {
        let idx = WordIndex::build();
        let ranks = idx.prefix_matches("ca", 5);
        assert!(!ranks.is_empty());
        // ranks already filtered to "ca…"; ensure ascending frequency rank.
        assert!(ranks.windows(2).all(|w| w[0] < w[1]));
        for r in &ranks {
            assert!(idx.word(*r).starts_with("ca"));
        }
    }
}
